### ISSUE TITLE
Error in sessions

### ISSUE THREAD

**Issue by jamilaguichelaar** [LCBC-UiO/js_mri_proc_status#12]
Since the wave code is added the sessions are not correct for quite some subjects. For example: There is an entry for subject 1700151 with wave code 4 but the session is "ses-02ousPrisma.2".

**Comment by Athanasiamo** [comment]
I did the wave code adding super quick and in a slightly lazy manner. Some of them might need fixing. But its data just like anything else, really, so you should be able to edit them through the same interface as other data

**Comment by jamilaguichelaar** [comment]
I can change everything in the interface except for the subject and session. All the wave three entries are ses-02ousPrisma.1 and all the wave four entries are ses-02ousPrisma.2. It is a bit too much to change it by hand. But we can look at it after you are back from vacation. Have a great vacation!

**Comment by Athanasiamo** [comment]
hm :P sounds like I did a superduper bad job. I really did think I had that fixed, I can have a peak at it now. I'm not on holiday this week :) 

But I'm not liking the `.1` at the end. My local version is not doing it, but that seems to happen on TSD. I definitely need to look more into that, related to #1
